server :
  port : 8080

spring:
  application:
    name: movieBackend

  datasource:
    url: jdbc:postgresql://localhost:5432/movie
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update